usethis::use_package("HDInterval")
usethis::use_package("ggplot2")
usethis::use_package("emdist")
usethis::use_package("vroom")
usethis::use_package("lme4")
usethis::use_package("dplyr")
usethis::use_package("plyr")
usethis::use_package("stringr")
usethis::use_package("purrr")
usethis::use_package("httr")
usethis::use_package("progress")
usethis::use_package("lubridate")
usethis::use_package("tidyr")
usethis::use_package("tibble")
usethis::use_package("rlang")
golem::add_module(name = "article")
golem::add_module(name = "read_data")
golem::add_module(name = "main_confirmatory")
golem::add_module(name = "exploratory")
golem::add_module(name = "robustness")
golem::add_module(name = "summary")
golem::add_module(name = "time_machine")
golem::add_module(name = "footer")
usethis::use_pipe()
golem::add_fct("helpers") 
golem::add_utils("helpers")
golem::add_js_file("script")
golem::add_js_handler("handlers")
golem::add_css_file("custom")
usethis::use_data_raw(name = "analysis_params", open = FALSE) 
usethis::use_data_raw(name = "example_m0", open = FALSE) 
usethis::use_data_raw(name = "example_m1", open = FALSE) 
usethis::use_test("app" )
usethis::use_vignette("use_pkg")
usethis::use_vignette("use_app")
devtools::build_vignettes()
usethis::use_github()
usethis::use_travis()
usethis::use_appveyor()
rstudioapi::navigateToFile("dev/03_deploy.R")
devtools::document()
devtools::load_all()
usethis::use_code_of_conduct()
usethis::use_pkgdown()
usethis::use_github_action(url = "https://raw.githubusercontent.com/r-lib/actions/master/examples/pkgdown.yaml")
# Modified the yaml based on https://github.com/marton-balazs-kovacs/tenzing/blob/master/.github/workflows/pkgdown.yaml
pkgdown::build_site()